const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.DESIGN_BROWSER_CHANNEL||'msedge'}),page=await browser.newPage();
  const errors=[],remote=[],checks=[],contrasts=[],flows=[],consoleErrors=[];
  page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url())});
  page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
  const open=()=>page.goto(pathToFileURL(path.join(__dirname,'preview','weekly-review.html')).href);
  const api=(fn,arg)=>page.evaluate(({fn,arg})=>eval('('+fn+')')(document.getElementById('dailys-review').dailysPreview,arg),{fn:String(fn),arg});
  const set=(scenario,condition='terisi',theme='terang')=>api((a,v)=>{Object.assign(a.design,v);a.render()},{scenario,condition,theme});
  const overflow=()=>page.evaluate(()=>[...document.querySelectorAll('body *')].filter(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width&&r.height&&s.visibility!=='hidden'&&s.display!=='none'&&!el.closest('dialog:not([open])')&&(r.left< -1||r.right>innerWidth+1||!['INPUT','TEXTAREA'].includes(el.tagName)&&el.clientWidth>0&&el.scrollWidth>el.clientWidth+2)}).map(el=>el.tagName+'#'+el.id+'.'+el.className).slice(0,12));
  const contrast=()=>page.evaluate(()=>{
    const rgb=s=>(s.match(/[\d.]+/g)||[]).map(Number),lum=v=>v.slice(0,3).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4}).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0),out=[];
    for(const el of document.querySelectorAll('#dailys-review *')){if(el.closest('dialog:not([open])')||!el.getBoundingClientRect().width||![...el.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()))continue;let bg=el;while(bg&&rgb(getComputedStyle(bg).backgroundColor)[3]===0)bg=bg.parentElement;if(!bg)continue;const s=getComputedStyle(el),a=lum(rgb(s.color)),b=lum(rgb(getComputedStyle(bg).backgroundColor)),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05),large=parseFloat(s.fontSize)>=24||parseFloat(s.fontSize)>=18.66&&parseFloat(s.fontWeight)>=700;if(ratio<(large?3:4.5)-.02)out.push({text:el.textContent.trim().slice(0,60),ratio})}
    return out;
  });
  const views=[['gate','terisi'],['before','terisi'],['completed','terisi'],['empty','terisi'],['fresh','terisi'],['gate','kosong'],['gate','memuat'],['gate','gagal']];
  for(const width of [1440,1056,860,736,680,440,392,352])for(const theme of ['terang','gelap'])for(const [scenario,condition]of views){await page.setViewportSize({width,height:3000});await open();await set(scenario,condition,theme);assert.deepEqual(await overflow(),[],`${width} ${theme} ${scenario} ${condition}`);checks.push({width,theme,scenario,condition})}
  for(const theme of ['terang','gelap'])for(const [scenario,condition]of views){await page.setViewportSize({width:1056,height:3000});await open();await set(scenario,condition,theme);const failures=await contrast();assert.deepEqual(failures,[],`${theme} ${scenario} ${condition} contrast`);contrasts.push({theme,scenario,condition,failures})}
  await page.setViewportSize({width:1056,height:1100});await open();
  const initialSummary=await api(a=>a.summary());assert(initialSummary.activity.completed>=initialSummary.pomodoro.completed_sessions+initialSummary.timebox.completed+initialSummary.habit.done);assert.equal(initialSummary.activity.planned,initialSummary.activity.completed+initialSummary.activity.skipped+initialSummary.activity.not_started);
  await page.locator('[data-savejournal]').click();assert.equal(await api(a=>a.getReview().status),'draft');
  await page.locator('[data-complete]').click();assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('[aria-invalid=true]').count(),2);assert.equal(await page.evaluate(()=>document.activeElement.id),'dr-evaluation');
  await page.locator('#dr-evaluation').fill('Evaluasi uji');await page.locator('#dr-focus').fill('Fokus uji');
  assert(await page.locator('[data-activate]').first().isDisabled());
  await assert.rejects(()=>api(a=>a.promote('p1',{judul:'X',target_date:'2026-09-16'},'gated')));
  const source=await api(a=>a.getCandidates());await page.locator('[data-fromcandidate="c1"]').click();await page.locator('#dr-draftdate').fill('2026-09-21');await page.locator('#dr-draftform button[type=submit]').click();assert((await page.locator('#dr-formerror').textContent()).includes('14–20'));assert.equal(await api(a=>a.getDrafts().length),2);
  await page.locator('#dr-draftdate').fill('2026-09-15');await page.locator('#dr-draftform button[type=submit]').click();assert.equal(await api(a=>a.getDrafts().length),3);assert.deepEqual(await api(a=>a.getCandidates()),source);assert.equal(await api(a=>a.getDrafts()[2].source_entity_id),'c1');
  await page.locator('[data-editdraft="p3"]').click();await page.locator('#dr-drafttitle').fill('Laporan lanjutan');await page.keyboard.press('Enter');assert.equal(await api(a=>a.getDrafts()[2].judul),'Laporan lanjutan');
  await api(a=>{a.getDrafts()[2].target_date='2026-09-21';a.render()});await page.locator('[data-complete]').click();assert.equal(await page.locator('dialog[open]').count(),0);assert((await page.locator('#dr-complete-error').textContent()).includes('Perbaiki'));
  await api(a=>{a.getDrafts()[2].target_date='2026-09-15';a.render()});await page.locator('[data-complete]').click();assert(await page.locator('dialog[open]').isVisible());await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.hasAttribute('data-complete')),true);
  await page.locator('[data-complete]').click();await page.locator('[data-confirmcomplete]').click();assert.equal(await api(a=>a.gate()),false);assert.equal(await api(a=>a.getReview().status),'completed');assert.equal(await api(a=>a.getDrafts().filter(d=>d.status==='draft').length),3);
  const snapshot=await api(a=>a.getReview().summary_snapshot),cutoff=await api(a=>a.getReview().summary_cutoff_at);await api(a=>{a.getSourceSummary().activity.completed=36;a.render()});await page.locator('#dr-evaluation').fill('Evaluasi diperbarui');await page.locator('[data-savejournal]').click();assert.deepEqual(await api(a=>a.getReview().summary_snapshot),snapshot);assert.equal(await api(a=>a.getReview().summary_cutoff_at),cutoff);assert.equal(await api(a=>a.summary().activity.completed),33);
  await page.locator('#dr-focus').fill(' ');await page.locator('[data-savejournal]').click();assert(await page.locator('#dr-focus[aria-invalid=true]').isVisible());await page.locator('#dr-focus').fill('Fokus diperbarui');await page.locator('[data-savejournal]').click();flows.push('empty draft save; mandatory journals; invalid draft blocks completion; offline completion opens gate with drafts remaining; frozen summary after source/text edit');
  await page.locator('[data-activate="p1"]').click();await page.locator('#dr-estimate').fill('0');await page.locator('#dr-promotionform button[type=submit]').click();assert((await page.locator('#dr-formerror').textContent()).includes('positif'));await page.locator('#dr-estimate').fill('30');await page.locator('#dr-promotionform button[type=submit]').click();assert.equal(await api(a=>a.getDrafts()[0].status),'promoted');assert.equal(await page.locator('[data-activate="p1"]').count(),0);
  assert.equal(await api(a=>a.workload()[2].task_count),2);assert.equal(await api(a=>a.workload()[2].estimated_minutes),30);assert.equal(await api(a=>a.workload()[2].unestimated_count),1);
  const count=await api(a=>a.getTargets().length),first=await api(a=>a.getTargets().find(t=>t.id==='example-target-p1-tugas'));const retry=await api(a=>a.promote('p1',{judul:'Latihan query transaksi',target_date:'2026-09-16'},'example-promotion-p1'));assert.equal(retry.id,first.id);assert.equal(await api(a=>a.getTargets().length),count);await assert.rejects(()=>api(a=>a.promote('p1',{judul:'X'},'new-key')));
  await page.locator('[data-target="p1"]').click();assert((await page.locator('dialog').innerText()).includes(first.id));await page.keyboard.press('Escape');
  await page.locator('[data-deletedraft="p3"]').click();await page.locator('[data-discard="p3"]').click();assert.equal(await api(a=>a.getDrafts()[2].status),'discarded');assert.equal(await page.locator('[data-editdraft="p3"]').count(),0);
  await page.locator('[data-activate="p2"]').click();await page.locator('#dr-end').fill('08:00');await page.locator('#dr-promotionform button[type=submit]').click();assert((await page.locator('#dr-formerror').textContent()).includes('setelah'));await page.locator('#dr-end').fill('10:00');await page.locator('#dr-promotionform button[type=submit]').click();assert.equal(await api(a=>a.getDrafts()[1].promoted_entity_type),'timebox');flows.push('Task promotion updates workload; same-command retry reuses target; second promotion rejected; promoted/discarded history immutable; Timebox times validated');
  await open();await set('before');assert.equal(await api(a=>a.gate()),false);assert(await page.locator('[data-complete]').isEnabled());await page.locator('[data-newdraft]').click();await page.locator('#dr-drafttype').selectOption('activity');await page.locator('#dr-drafttitle').fill('Activity bebas');await page.locator('#dr-draftform button[type=submit]').click();await page.locator('[data-activate="p3"]').click();await page.locator('#dr-start').fill('');await page.locator('#dr-end').fill('');await page.locator('#dr-promotionform button[type=submit]').click();assert.equal(await api(a=>a.getDrafts()[2].promoted_entity_type),'activity');flows.push('manual review before trigger; free Activity draft and all-day promotion');
  await open();await page.locator('#dr-evaluation').fill('Jangan hilang');await page.locator('#reference-condition').selectOption('gagal');assert.equal(await page.locator('#dr-evaluation').inputValue(),'Jangan hilang');await page.locator('[data-retry]').first().click();assert.equal(await page.locator('#dr-evaluation').inputValue(),'Jangan hilang');assert.equal(await api(a=>a.getDrafts().length),2);
  await page.locator('[data-deletedraft="p2"]').click();await page.locator('[data-confirmdelete="p2"]').click();assert.equal(await api(a=>a.getDrafts().length),1);assert.equal(await api(a=>a.getCandidates().length),3);
  await set('empty');assert.equal(await api(a=>a.summary().activity.completion_rate),0);assert.equal(await page.locator('.dr-worktable tbody tr').count(),7);assert((await page.locator('.dr-candidates').innerText()).includes('Tidak ada kandidat'));await set('fresh');assert.equal(await page.locator('textarea').count(),0);assert((await page.locator('#dr-content').innerText()).includes('20 September pukul 09.00'));flows.push('read failure/retry preserves journals/drafts; deletion leaves source; zero rate and seven zero days; fresh install has no partial review');
  const modalCases=[];
  for(const width of [1440,352])for(const theme of ['terang','gelap'])for(const type of ['tugas','activity','timebox']){
    await page.setViewportSize({width,height:1100});await open();await set('before','terisi',theme);await page.locator('[data-newdraft]').click();await page.locator('#dr-drafttitle').fill('Judul contoh sangat panjang untuk pemeriksaan form dan target');await page.locator('#dr-drafttype').selectOption(type);assert.deepEqual(await overflow(),[],'draft modal '+width+' '+theme);await page.locator('#dr-draftform button[type=submit]').click();await page.locator('[data-activate="p3"]').click();assert.deepEqual(await overflow(),[],'promotion '+type+' '+width+' '+theme);const failures=await contrast();assert.deepEqual(failures,[],type+' modal contrast');assert.equal(await page.evaluate(()=>document.activeElement.id),'dr-targettitle');await page.keyboard.press('Tab');assert((await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle))!=='none');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.dataset.activate),'p3');modalCases.push({width,theme,type})
  }
  await page.setViewportSize({width:352,height:1100});await open();await page.locator('[data-candidate="c1"]').click();await page.waitForURL('**/tugas.html');assert.deepEqual(await overflow(),[]);
  await open();await page.locator('[data-home]').click();await page.waitForURL('**/home.html');await page.locator('#dh-reviewopen').click();await page.waitForURL('**/weekly-review.html');flows.push('candidate source route to Tasks; Home shortcut and return route');
  for(const width of [1440,352]){await page.setViewportSize({width,height:3000});await open();await set('gate');await page.locator('#dailys-review').screenshot({path:path.join(__dirname,'mockups','weekly-review-'+(width===1440?'desktop':'mobile')+'.png')})}
  await page.setViewportSize({width:1056,height:3000});await open();await set('completed','terisi','gelap');await page.locator('#dailys-review').screenshot({path:path.join(__dirname,'evidence','weekly-review-completed-dark.png')});
  assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.deepEqual(consoleErrors,[]);
  fs.writeFileSync(path.join(__dirname,'evidence','qa-review-results.json'),JSON.stringify({status:'PASS',responsiveChecks:checks.length,checks,contrasts,modalCases,flows,jsErrors:errors,consoleErrors,remoteRequests:remote},null,2)+'\n');
  await browser.close();console.log(`PASS: ${checks.length} responsive cases, ${contrasts.length} contrast views, ${modalCases.length} promotion modal cases; journal/gate/draft/promotion/workload/freeze/routing flows; no JS errors or remote requests.`);
})().catch(e=>{console.error(e);process.exit(1)});
