const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');const {chromium}=require('playwright');
(async()=>{
 const base=__dirname,browser=await chromium.launch({headless:true,channel:process.env.DESIGN_BROWSER_CHANNEL||'msedge'}),page=await browser.newPage();
 const errors=[],remote=[],checks=[],contrast=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url())});
 const open=()=>page.goto(pathToFileURL(path.join(base,'preview','pusat-sync.html')).href);
 const api=(fn,arg)=>page.evaluate(({fn,arg})=>{const a=document.getElementById('dailys-sync').dailysPreview;return eval('('+fn+')')(a,arg)},{fn:String(fn),arg});
 async function overflow(){return page.evaluate(()=>[...document.querySelectorAll('#dailys-sync *')].filter(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width&&r.height&&s.display!=='none'&&s.visibility!=='hidden'&&!el.closest('dialog:not([open])')&&(r.left< -1||r.right>innerWidth+1||el.clientWidth>0&&el.scrollWidth>el.clientWidth+2)}).map(el=>el.tagName+'#'+el.id+'.'+el.className).slice(0,10))}
 async function fixture(view){await open();await api((a,view)=>{a.design.screen=view.startsWith('onboard')?'onboarding':view.startsWith('conflict')||view==='task'||view==='ledger'?'conflicts':'sync';a.design.condition='terisi';if(view==='task'||view==='ledger')a.setRoute({type:'review',id:view==='task'?'task1':'ledger1'});else if(view.startsWith('recovery'))a.setRoute({type:'recovery'});else if(view.startsWith('onboard')){a.onboarding.step=Number(view.slice(-1));a.render()}else a.render()},view);if(['devices','history'].includes(view))await page.locator('[data-synctab="'+view+'"]').click();if(view==='recovery-post'){for(let i=0;i<2;i++){await page.locator('[data-recovernext]').click();await page.waitForTimeout(390)}}}
 const views=['sync','devices','history','conflicts','task','ledger','onboard0','onboard1','onboard2','onboard3','recovery-pre','recovery-post'];
 for(const width of [1440,1056,860,736,680,440,392,352])for(const theme of ['terang','gelap'])for(const view of views){await page.setViewportSize({width,height:3000});await fixture(view);await api((a,theme)=>{a.design.theme=theme;a.render()},theme);const issues=await overflow();assert.deepEqual(issues,[],`${view} ${width} ${theme}`);checks.push({view,width,theme});}
 for(const theme of ['terang','gelap'])for(const view of ['sync','conflicts','task','ledger','onboard0','recovery-pre']){await page.setViewportSize({width:1056,height:3000});await fixture(view);await api((a,theme)=>{a.design.theme=theme;a.render()},theme);const failures=await page.evaluate(()=>{
  const rgb=s=>(s.match(/[\d.]+/g)||[]).map(Number),lum=v=>v.slice(0,3).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4}).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0);
  const out=[];for(const el of document.querySelectorAll('#dailys-sync *')){if(el.matches(':disabled')||el.closest(':disabled,dialog:not([open])')||!el.getBoundingClientRect().width||!el.childNodes.length||![...el.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()))continue;const cs=getComputedStyle(el);let bg=el;while(bg&&rgb(getComputedStyle(bg).backgroundColor)[3]===0)bg=bg.parentElement;if(!bg)continue;const a=lum(rgb(cs.color)),b=lum(rgb(getComputedStyle(bg).backgroundColor)),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05),size=parseFloat(cs.fontSize),large=size>=24||size>=18.66&&parseFloat(cs.fontWeight)>=700;if(ratio<(large?3:4.5)-.02)out.push({text:el.textContent.trim().slice(0,60),ratio});}return out;
 });assert.deepEqual(failures,[],`${view} ${theme} contrast`);contrast.push({view,theme,failures});}
 for(const screen of ['sync','conflicts'])for(const condition of ['kosong','memuat','gagal']){await open();await api((a,v)=>{a.design.screen=v.screen;a.design.condition=v.condition;a.render()},{screen,condition});if(condition==='gagal'){assert(await page.locator('[data-retry]').isVisible());await page.locator('[data-retry]').click()}else assert((await page.locator('#ds-content').innerText()).includes(condition==='memuat'?'Membaca status lokal':screen==='sync'?'Tidak ada antrean':'Tidak ada konflik'));}
 for(const scenario of ['offline','failure','unregistered','revoked','recovery','ready']){await open();await page.locator('#ds-scenario').selectOption(scenario);assert.deepEqual(await overflow(),[],scenario);if(['offline','revoked','recovery'].includes(scenario))assert(await page.locator('[data-sync]').isDisabled());}
 async function chooseTask(){await page.locator('#ds-screen').selectOption('conflicts');await page.locator('[data-review="task1"]').click();await page.locator('[data-choice="task1|schedule"][value="local"]').check();await page.locator('[data-choice="task1|deskripsi"][value="server"]').check();await page.locator('[data-prepare]').click();await page.locator('[data-submitreview]').click();}
 async function syncFromReview(){await page.locator('[data-conflicts]').click();await page.locator('[data-gosync]').click();await page.locator('[data-sync]').click();await page.waitForTimeout(500)}
 await open();await chooseTask();assert.equal(await api(a=>a.reviews[0].status),'submitted');assert.equal(await api(a=>a.requests[0].base_server_revision),101);assert.equal(await api(a=>a.requests[0].resolution_of),'review-task-101');assert(await page.locator('[data-prepare]').isDisabled());await syncFromReview();assert.equal(await api(a=>a.reviews[0].status),'resolved');assert.equal(await api(a=>a.reviews[1].status),'pending_review');assert.equal(await api(a=>a.pending.length),0);
 await open();await page.locator('#ds-result').selectOption('server_changed');await chooseTask();await syncFromReview();assert.equal(await api(a=>a.reviews[0].reason),'server_changed');assert.equal(await api(a=>a.reviews[0].choices.schedule),undefined);assert.equal(await api(a=>a.reviews[0].choices.deskripsi),'server');assert.equal(await api(a=>a.reviews[0].change),'resolution-1');
 await open();await page.locator('#ds-result').selectOption('rejected');await chooseTask();await syncFromReview();assert.equal(await api(a=>a.reviews[0].status),'pending_review');assert.equal(await api(a=>a.requests[0].status),'rejected');
 await open();await page.locator('#ds-screen').selectOption('conflicts');await page.locator('[data-review="task1"]').click();assert.equal(await api(a=>a.reviews[0].status),'pending_review');await page.locator('[data-entireserver]').click();await page.locator('[data-discardentire]').click();assert.equal(await api(a=>a.reviews[0].status),'discarded');assert.equal(await api(a=>a.requests.length),0);
 await open();await page.locator('#ds-scenario').selectOption('offline');await chooseTask();assert.equal(await api(a=>a.reviews[0].status),'submitted');assert.equal(await api(a=>a.requests[0].status),'queued');
 await open();await page.locator('#ds-screen').selectOption('conflicts');await page.locator('[data-review="ledger1"]').click();await page.locator('[data-choice="ledger1|ledger"][value="local"]').check();assert.equal(await page.evaluate(()=>document.activeElement.dataset.choice),'ledger1|ledger');await page.keyboard.press('Tab');assert((await page.evaluate(()=>document.activeElement.tagName))!=='BODY');assert((await page.locator('.ds-impact').innerText()).includes('−Rp5.000'));await page.locator('[data-prepare]').click();assert.deepEqual(await overflow(),[],'ledger dialog');await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 await open();await page.locator('[data-rejected]').click();await page.locator('#ds-rejectedform button[type=submit]').click();assert.equal(await api(a=>a.rejected[0].status),'corrected');assert.equal(await api(a=>a.pending.length),4);
 await open();await page.locator('#ds-scenario').selectOption('recovery');await page.locator('[data-recovery]').first().click();await page.locator('[data-recovernext]').click();await page.waitForTimeout(390);assert.equal(await api(a=>a.getRecovery().copyVerified),true);assert.equal(await api(a=>a.getRecovery().snapshotComplete),false);await page.locator('#ds-snapshot').selectOption('failure');await page.locator('[data-recovernext]').click();await page.waitForTimeout(390);assert.equal(await api(a=>a.getRecovery().snapshotComplete),false);assert.equal(await api(a=>a.getRecovery().copyVerified),true);await page.locator('#ds-snapshot').selectOption('expired');await page.locator('[data-recovernext]').click();await page.waitForTimeout(390);assert((await page.locator('#ds-notice').innerText()).includes('kedaluwarsa'));await page.locator('#ds-snapshot').selectOption('accepted');await page.locator('[data-recovernext]').click();await page.waitForTimeout(390);assert.equal(await api(a=>a.getRecovery().snapshotComplete),true);assert.equal(await api(a=>a.requests.length),0);assert(await page.locator('[data-recoverycheck="k3"]').isDisabled());assert(await page.locator('[data-recoverycheck="k4"]').isDisabled());await page.locator('[data-recoverycheck="k1"]').check();await page.locator('[data-recoverycheck="k2"]').check();await page.locator('[data-replayprepare]').click();assert((await page.locator('.ds-impact').innerText()).includes('−Rp75.000'));await page.locator('[data-replayconfirm]').click();assert.equal(await api(a=>a.requests.length),2);assert.equal(await api(a=>a.recovery[0].status),'replayed');await page.locator('[data-manualrecovery]').click();await page.locator('[data-discardrecovery]').click();assert.equal(await api(a=>a.recovery[3].status),'discarded');
 await page.setViewportSize({width:352,height:3000});await open();await page.locator('#ds-scenario').selectOption('offline');await page.locator('#ds-screen').selectOption('onboarding');await page.locator('[data-language][value=en]').check();assert.equal(await page.locator('#ds-content h1').textContent(),'Choose language & time');await page.locator('[data-timezone]').selectOption('Asia/Jayapura');await page.locator('#ds-onboardform button[type=submit]').click();await page.locator('[data-register]').click();await page.waitForTimeout(390);assert.equal(await api(a=>a.onboarding.registration),'failed');await page.locator('#ds-onboardform button[type=submit]').click();await page.locator('[data-skipaccount]').click();await page.locator('#ds-onboardform button[type=submit]').click();assert.equal(await api(a=>a.onboarding.complete),true);assert.equal(await api(a=>a.onboarding.useAccount),false);assert.equal(await api(a=>a.design.scenario),'unregistered');assert.equal(await api(a=>a.onboarding.timezone),'Asia/Jayapura');assert.equal(await page.locator('input[type=password]').count(),0);
 await open();await page.locator('#ds-screen').selectOption('onboarding');await page.locator('#ds-onboardform button[type=submit]').click();await page.locator('[data-register]').click();await page.waitForTimeout(390);assert.equal(await api(a=>a.onboarding.registration),'active');assert(await page.locator('[data-device]').isDisabled());await page.locator('#ds-onboardform button[type=submit]').click();await page.locator('[data-account]').fill(' ');await page.locator('#ds-onboardform button[type=submit]').click();assert((await page.locator('#ds-onboarderror').innerText()).includes('Isi nama akun'));await page.locator('[data-account]').fill('Dompet kampus');await page.locator('[data-opening]').fill('50000');await page.locator('#ds-onboardform button[type=submit]').click();await page.locator('#ds-onboardform button[type=submit]').click();assert.equal(await api(a=>a.onboarding.complete),true);assert.equal(await api(a=>a.onboarding.opening),'50000');await page.locator('[data-onboardhome]').click();await page.waitForURL('**/home.html');assert(await page.locator('#dailys-home').isVisible());
 await fixture('onboard2');await page.locator('[data-opening]').fill('-5000');await page.locator('#ds-onboardform button[type=submit]').click();assert.equal(await api(a=>a.onboarding.step),3);assert((await page.locator('.ds-summary').innerText()).includes('−Rp5.000'));
 for(const width of [1440,352])for(const [id,view]of [['pusat-sync','sync'],['review-konflik','task'],['onboarding','onboard0']]){await page.setViewportSize({width,height:3000});await fixture(view);await api(a=>{a.design.theme='terang';a.render()});await page.locator('#dailys-sync').screenshot({path:path.join(base,'mockups',id+'-'+(width===1440?'desktop':'mobile')+'.png')});}
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);fs.writeFileSync(path.join(base,'evidence','qa-sync-results.json'),JSON.stringify({status:'PASS',responsiveChecks:checks.length,checks,contrast,jsErrors:errors,remoteRequests:remote,flows:['group resolution accepted','server_changed new review','rejected review retained','entire server discard without request','offline resolution queued','ledger impact','rejection correction new identity','copy before replacement','snapshot failure and expiry preserve copy','explicit replay consent and money impact','superseded no replay','ambiguous tombstone manual review','onboarding English/timezone','registration failure offline completion','optional account skip','account validation and registered completion','onboarding to Home offline route']},null,2)+'\n');await browser.close();console.log('PASS: 192 responsive cases, 12 contrast views, conflict/recovery/onboarding flows; no JS errors or network requests.');
})().catch(e=>{console.error(e);process.exit(1)});
